// Code generated by goyacc -o parser/parser.go parser/parser.y. DO NOT EDIT.

//line parser/parser.y:2
package parser

import __yyfmt__ "fmt"

//line parser/parser.y:2

import (
	"github.com/monsterxx03/sqlpar/value"
	"strconv"
)

func setResult(yylex interface{}, stmt Statement) {
	yylex.(*Lexer).result = stmt
}

//line parser/parser.y:15
type yySymType struct {
	yys            int
	str            string
	value          value.Value
	expr           Expr
	stmt           Statement
	sel            *Select
	sel_field      SelectField
	sel_field_list SelectFieldList
	orderBy        OrderBy
	where          *Where
	limit          *Limit
}

const ILLEGAL = 57346
const SELECT = 57347
const FROM = 57348
const WHERE = 57349
const ORDER_BY = 57350
const LIMIT = 57351
const OFFSET = 57352
const IDENT = 57353
const INTEGER = 57354
const FLOAT = 57355
const AND = 57356
const OR = 57357
const NOT = 57358
const LE = 57359
const GE = 57360
const NE = 57361
const IS = 57362
const LIKE = 57363
const IN = 57364

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ILLEGAL",
	"SELECT",
	"FROM",
	"WHERE",
	"ORDER_BY",
	"LIMIT",
	"OFFSET",
	"IDENT",
	"INTEGER",
	"FLOAT",
	"AND",
	"OR",
	"NOT",
	"'!'",
	"'='",
	"'<'",
	"'>'",
	"LE",
	"GE",
	"NE",
	"IS",
	"LIKE",
	"IN",
	"','",
	"'*'",
	"'('",
	"')'",
	"'\"'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser/parser.y:199

func Parse(s string) (Statement, error) {
	l := NewLexer(s)
	yyParse(l)
	return l.result, l.err
}

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 10,
	29, 9,
	-2, 11,
}

const yyPrivate = 57344

const yyLast = 51

var yyAct = [...]int{

	44, 23, 48, 12, 10, 39, 20, 13, 31, 32,
	33, 34, 35, 36, 11, 26, 28, 29, 5, 43,
	25, 7, 38, 24, 46, 6, 45, 37, 8, 27,
	40, 41, 17, 47, 15, 12, 8, 8, 16, 22,
	19, 4, 1, 21, 18, 3, 2, 42, 30, 9,
	14,
}
var yyPact = [...]int{

	36, -1000, -1000, -1000, -7, 8, -1000, -1000, -1000, -22,
	-1000, 23, -7, -7, 33, -1000, -1000, -24, 30, 4,
	-1000, -1000, 17, 2, -10, 4, -1000, -5, 4, 4,
	-12, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 14, 12,
	-1000, -1000, -1000, 22, -1000, -1000, -1000, -29, -1000,
}
var yyPgo = [...]int{

	0, 1, 50, 23, 49, 48, 47, 46, 45, 25,
	18, 44, 43, 42,
}
var yyR1 = [...]int{

	0, 13, 7, 8, 10, 10, 9, 9, 9, 4,
	2, 3, 11, 11, 1, 1, 1, 1, 12, 12,
	12, 12, 6, 6, 5, 5, 5, 5, 5, 5,
}
var yyR2 = [...]int{

	0, 1, 1, 6, 1, 3, 1, 1, 4, 1,
	1, 1, 0, 2, 3, 3, 3, 2, 0, 2,
	4, 4, 3, 1, 1, 1, 1, 1, 1, 1,
}
var yyChk = [...]int{

	-1000, -13, -7, -8, 5, -10, -9, 28, -3, -4,
	11, 6, 27, 29, -2, 11, -9, -10, -11, 7,
	30, -12, 9, -1, -3, 16, 11, 12, 14, 15,
	-5, 18, 19, 20, 21, 22, 23, -1, 27, 10,
	-1, -1, -6, 31, 12, 12, 12, 11, 31,
}
var yyDef = [...]int{

	0, -2, 1, 2, 0, 0, 4, 6, 7, 0,
	-2, 0, 0, 0, 12, 10, 5, 0, 18, 0,
	8, 3, 0, 13, 0, 0, 11, 19, 0, 0,
	0, 24, 25, 26, 27, 28, 29, 17, 0, 0,
	15, 16, 14, 0, 23, 20, 21, 0, 22,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 17, 31, 3, 3, 3, 3, 3,
	29, 30, 28, 3, 27, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	19, 18, 20,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
	26,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:51
		{
			setResult(yylex, yyDollar[1].stmt)
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:57
		{
			yyVAL.stmt = yyDollar[1].sel
		}
	case 3:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/parser.y:63
		{
			yyVAL.sel = NewSelect(yyDollar[2].sel_field_list, yyDollar[4].str, yyDollar[5].where, yyDollar[6].limit)
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:71
		{
			yyVAL.sel_field_list = SelectFieldList{yyDollar[1].sel_field}
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:75
		{
			yyVAL.sel_field_list = append(yyVAL.sel_field_list, yyDollar[3].sel_field)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:82
		{
			yyVAL.sel_field = &StarExpr{}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:86
		{
			yyVAL.sel_field = &ColExpr{yyDollar[1].str}
		}
	case 8:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:90
		{
			yyVAL.sel_field = &FuncExpr{Name: yyDollar[1].str, Fields: yyDollar[3].sel_field_list}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:96
		{
			yyVAL.str = yyDollar[1].str
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:102
		{
			yyVAL.str = yyDollar[1].str
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:109
		{
			yyVAL.str = yyDollar[1].str
		}
	case 12:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:114
		{
			yyVAL.where = nil
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:118
		{
			yyVAL.where = NewWhere(yyDollar[2].expr)
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:124
		{
			yyVAL.expr = &ComparisonExpr{Left: yyDollar[1].str, Operator: yyDollar[2].str, Right: yyDollar[3].value}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:128
		{
			yyVAL.expr = &AndExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:132
		{
			yyVAL.expr = &OrExpr{Left: yyDollar[1].expr, Right: yyDollar[3].expr}
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:136
		{
			yyVAL.expr = &NotExpr{Expr: yyDollar[2].expr}
		}
	case 18:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/parser.y:141
		{
			yyVAL.limit = nil
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:145
		{
			limit, _ := strconv.Atoi(yyDollar[2].str)
			yyVAL.limit = &Limit{Rowcount: limit}
		}
	case 20:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:150
		{
			offset, _ := strconv.Atoi(yyDollar[2].str)
			limit, _ := strconv.Atoi(yyDollar[4].str)
			yyVAL.limit = &Limit{Offset: offset, Rowcount: limit}
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/parser.y:156
		{
			limit, _ := strconv.Atoi(yyDollar[2].str)
			offset, _ := strconv.Atoi(yyDollar[4].str)
			yyVAL.limit = &Limit{Offset: offset, Rowcount: limit}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:164
		{
			yyVAL.value = value.Str{Val: yyDollar[2].str}
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:169
		{
			v, _ := strconv.Atoi(yyDollar[1].str)
			yyVAL.value = value.Int{Val: int64(v)}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:176
		{
			yyVAL.str = "="
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:180
		{
			yyVAL.str = "<"
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:184
		{
			yyVAL.str = ">"
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:188
		{
			yyVAL.str = "<="
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:192
		{
			yyVAL.str = ">="
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:196
		{
			yyVAL.str = "!="
		}
	}
	goto yystack /* stack new state and value */
}
